### ISSUE TITLE
Open Source License for this code?

### ISSUE THREAD

**Issue by rkosinski941** [sitepoint-editors/accessible-drag-and-drop#2]
Hi,

It looks like a lot of the code for sitepoint here on Gitbhub is MIT licensed.  Is this particular code licensed under MIT as well?

Thanks,
-Rich

**Comment by jameshibbard** [comment]
Good question. I believe so, but let me check. I'll get back to you once I have found out.

**Comment by jameshibbard** [comment]
Yup, can confirm that all example code on SitePoint is licensed under an MIT license, with the exception of specific circumstances where the author will retain or set the license (i.e., syndicated posts).
